language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true
 
r:
  - release
  - devel

bioc_packages:
    - impute

r_github_packages:
    - wilsontom/FIEmspro

r_packages:
    - covr
    - testthat
    - rlang
    - digest
    - devtools

after_success:
    - Rscript -e 'library(covr); codecov()'

notifications:
    email:
    on_success: change
    on_failure: change