language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true

apt_packages:
 - libnetcdf-dev
  - netcdf-bin

r:
  - release
  - devel

bioc_packages:
    - impute

r_github_packages:
    - aberhrml/FIEmspro

r_packages:
    - covr
    - testthat
    - rlang
    - digest
    - devtools
    - ncdf4

after_success:
    - Rscript -e 'library(covr); codecov()'

notifications:
    email:
    on_success: change
    on_failure: change