language: r

sudo: required
bioc_required: true
warnings_are_errors: true
 
bioc_packages:
    - impute

r_github_packages:
    - wilsontom/FIEmspro

r_packages:
    - covr
    - testthat

after_success:
    - Rscript -e 'library(covr); codecov()'

notifications:
    email:
    on_success: change
    on_failure: change