language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true

apt_packages:
 - libnetcdf-dev
 - netcdf-bin

r:
  - release
  - devel

r_github_packages:
  - thomasp85/patchwork

bioc_packages:
    - impute

after_success:
    - Rscript -e 'library(covr); codecov()'

notifications:
    email:
    on_success: change
    on_failure: change