
globalVariables(c('Class',
                  'Feature',
                  'Intensity',
                  'ID',
                  '-log10(Pvalue)',
                  '.',
                  'n',
                  'Count',
                  'Occupancy',
                  'data',
                  'Iteration',
                  'Feature1',
                  'Feature2',
                  'Intensity1',
                  'Intensity2',
                  'log2IntensityRatio',
                  'Method',
                  'Pairwise',
                  'Measure',
                  'Value',
                  'Mean',
                  'V1',
                  'V2',
                  'P1',
                  'P2',
                  'Score',
                  'Total',
                  'Relative Intensity',
                  'Colour',
                  'DF1',
                  'Dimension 1',
                  'Dimension 2',
                  'Index',
                  'Mode',
                  'RSD',
                  'TIC',
                  'r',
                  'SelectionFrequency',
                  'FPR',
                  'Pvalue'
                  ))